### ISSUE TITLE
Cannot view PDF over 1,5MB

### ISSUE THREAD

**Issue by erolkunman** [Drakonian/bc-pdf-viewer-full#1]
I tested this solution and found 1 big issue for me:
**It doesnt show contents of PDF files over 1,5MB in file size.**

Do You have some solution for that?

**Comment by Drakonian** [comment]
Looks like the browser can't render large PDFs as Base64 objects. I found the same problem even when using locally created HTML.
To fix this, I converted the Base64 object to a blob URL.

Fix is merged.
https://github.com/Drakonian/bc-pdf-viewer-full/pull/4
